# Generated by Django 6.0.5 on 2026-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="designs/")),
                ("tools_used", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("date", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=300)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profession", models.CharField(max_length=300)),
                ("hero_image", models.ImageField(upload_to="profile/")),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("short_bio", models.TextField()),
                ("phone", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=300)),
                ("google_map", models.TextField(blank=True)),
                ("resume", models.FileField(upload_to="resume/")),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("footer_description", models.TextField()),
                ("projects_completed", models.IntegerField(default=0)),
                ("years_experience", models.IntegerField(default=0)),
                ("technologies_used", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("technologies", models.CharField(max_length=300)),
                ("source_code", models.URLField(blank=True)),
                ("live_demo", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                ("percentage", models.IntegerField()),
            ],
        ),
    ]
