# Generated by Django 6.0.5 on 2026-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="google_map",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="hero_image",
        ),
    ]
