# Generated by Django 6.0.5 on 2026-05-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_profile_google_map_remove_profile_hero_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="facebook",
        ),
    ]
